#!/usr/bin/env bash

while read line; do
	case "${line}" in
	*youtu[\.b][be]*) ytURL="${line}" ;;
	[a-zA-Z0-9]*[\.\/]*[!\.]) ytURL="$(op "${line}" "##*'//'" '#*www\.' '%%\/*' '%\.*' '##*\.' '(--extractor ).' ".( '${line}')")" ;;
	*) continue
	esac
done < <({ zenity --forms --width 333 --title "YTDLazy - Video" --text "Provide gMapsAPI-compliant directions to the otherShoneys:" --add-entry="url" --add-entry="note" --separator=$'\n'\| | tee >(op '??=\|*' '//\|/' > ~/.tmp/${0##*\/}.note ; ) | op "?!=[$'\n'\|]*" ; } )

if [[ -n "${ytURL}" ]]; then
	ytdl-quick "${ytURL}" && notify-send "$(echo -e "Successfully downloaded:\n${ytURL}")" || notify-send "$(echo -e "FAILED to download:\n${ytURL}")"
else
	notify-send "no dice..."
	exit 1
fi

[[ -z "$(cat ~/.tmp/${0##*\/}.note)" ]] && rm ~/.tmp/${0##*\/}.note 2>/dev/null || mv ~/.tmp/${0##*\/}.note ~/Videos/YTDL/.Holding/$(date '+%Y%m%d')/${ytURL##*\/}.note
