#!/usr/bin/env bash

while read line; do
	[[ "${line}" != *youtu[\.b][be]* ]] || ytURL="${line}"
done < <({ zenity --forms --width 333 --title "YTDLazy - Audio" --text "Provide gMapsAPI-compliant directions to the otherShoneys:" --add-entry="url" --add-entry="note" --separator=$'\n'\| | tee >(op '??=\|*' '//\|/' > ~/.tmp/${0##*\/}.note ; ) | op "?!=[$'\n'\|]*" ; } )

if [[ -n "${ytURL}" ]]; then
	ytdl-quick -A "${ytURL}" && notify-send "$(echo -e "Successfully downloaded:\n${ytURL}")" || notify-send "$(echo -e "FAILED to download:\n${ytURL}")"
else
	notify-send "no dice..."
	exit 1
fi

[[ -z "$(cat ~/.tmp/${0##*\/}.note)" ]] && rm ~/.tmp/${0##*\/}.note 2>/dev/null || mv ~/.tmp/${0##*\/}.note ~/Music/YTDLA/$(date '+%Y%m%d')/${ytURL##*\/}.note
